name: Single Unit Test

on:
  workflow_call:
    inputs:
      gradleVersion:
        type: string
        required: true
        description: 'Gradle version â€“ see: https://github.com/gradle/gradle/releases'
      os:
        type: string
        required: true
        description: 'Operation system'
      script:
        type: string
        required: false
        description: 'Optional OS-dedicated script to run in the beginning'
      testName:
        type: string
        required: false
        description: 'Optional test name to run'

jobs:
  unitTests:
    name: Gradle ${{ inputs.gradleVersion }} @ ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    permissions:
      checks: write
    steps:

      - name: Run OS-dedicated script
        if: ${{ inputs.script }}
        run: ${{ inputs.script }}

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run Tests
        env:
          TEST_NAME: ${{ inputs.testName }}
        shell: bash
        run: |
          [ -z "$TEST_NAME" ] && TESTS="" || TESTS="--tests $TEST_NAME"
          
          ./gradlew check test \
            -PtestGradleVersion="${{ inputs.gradleVersion }}" \
            ${{ runner.os == 'Windows' && '-PtestGradleUserHome="C:\\testGradleHome"' || '' }} \
            $TESTS \
            --console=plain

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: "Unit Tests Report: Gradle ${{ inputs.gradleVersion }} @ ${{ inputs.os }}"
          path: "**/build/test-results/*/TEST-*.xml"
          reporter: java-junit

      - name: Collect Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-${{ inputs.gradleVersion }}-${{ runner.os }}
          path: |
            ${{ github.workspace }}/build/reports/tests
            ${{ github.workspace }}/build/reports/configuration-cache
