name: Manual Unit Tests
on:
  workflow_dispatch:
    inputs:
      testName:
        description: "Test name"
        required: false
        type: string
      gradleVersion:
        description: "Gradle Version"
        required: true
        type: string
        default: "8.14"
      os:
        description: "Operation System"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
  workflow_call:

jobs:
  unitTest:
    name: Gradle ${{ inputs.gradleVersion }} @ ${{ inputs.os }}
    uses: ./.github/workflows/reusable-single-unitTest.yml
    secrets: inherit
    permissions:
      checks: write
    with:
      gradleVersion: ${{ inputs.gradleVersion }}
      os: ${{ inputs.os }}
      testName: ${{ inputs.testName }}
